# Generated by Django 5.0.7 on 2024-08-02 10:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('fee_amount', models.IntegerField()),
                ('fee_date', models.DateField(default=django.utils.timezone.now)),
                ('image', models.ImageField(upload_to='members/')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
